name: pact-cli
description: A standalone pact command line executable using the ruby pact implementation and Traveling Ruby
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}\cli.sh
      shell: bash
      if: runner.os == 'windows'
    - run: D\\:\\a\\_actions\\you54f\\paction\\main\\cli.sh
      shell: bash
      if: runner.os != 'windows'
    - run: |
        "$pwd\pact\bin\" >> $env:GITHUB_PATH
      if: runner.os == 'windows'
      shell: powershell
