name: pact-cli
description: A standalone pact command line executable using the ruby pact implementation and Traveling Ruby
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: brew install you54f/pact/pact_broker
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
    - uses: MinoruSekine/setup-scoop@v1
      if: runner.os == 'windows'
    - run: |
        scoop bucket add pact https://github.com/you54f/scoop
        scoop install pact-broker
      if: runner.os == 'windows'
      shell: powershell
    - uses: pactflow/actions@main