name: Test cli.sh

on:
  push:
  workflow_dispatch:

jobs:
  local_install_script:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest]
        shell: [bash, sh]
      fail-fast: false
    defaults:
      run:
        shell: ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - run: ./cli.sh
        name: install via cli.sh
      - run: pact help
        name: pact help via ${{ matrix.shell }}

  windows_local_install_script:
    runs-on: windows-latest
    strategy:
      matrix:
        shell: [cmd, powershell, pwsh, bash, sh]
      fail-fast: false
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          "$pwd\pact\bin\" >> $env:GITHUB_PATH
        shell: powershell
        if: matrix.shell == 'powershell' || matrix.shell == 'pwsh' || matrix.shell == 'cmd'
      - run: ./cli.sh
        name: install via cli.sh
        shell: sh
      - run: pact.bat help
        name: pact.bat help via ${{ matrix.shell }}
