name: Build

on:
  push:
  workflow_dispatch:

jobs:
  ubuntu:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - run: ./cli.sh
        name: bash
        shell: bash
      - run: ./cli.sh
        name: sh
        shell: sh
      - run: curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/chore/install/bin_sh/install.sh | sh && pact/bin/pact help
      - run: rm -rf pact
      - run: wget -q https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/chore/install/bin_sh/install.sh -O- | sh && pact/bin/pact help
      - run: echo "PATH=${PATH}:${PWD}/pact/bin/" >> $GITHUB_ENV
      - run: pact help

  mac:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - run: ./cli.sh
      - run: |
          brew install pact-foundation/pact-ruby-standalone/pact-ruby-standalone
          pact help
        shell: bash
      - run: brew uninstall pact-ruby-standalone
      - run: curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/chore/install/bin_sh/install.sh | sh && pact/bin/pact help
      - run: echo "PATH=${PATH}:${PWD}/pact/bin/" >> $GITHUB_ENV
      - run: pact help

  windows:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - run: ./cli.sh
        shell: bash
      - run: |
          "$pwd\pact\bin\" >> $env:GITHUB_PATH
        if: runner.os == 'windows'
        shell: powershell
      - run: pact-broker.bat
        shell: cmd